name: space_server
version: 0.1.0
author: Heikki Haapala <hhaapala@gmail.com>
dependencies:
  logging: any
  siege_engine:
    path: /home/hhaapala/dart/siege_engine
  space_shared:
    path: /home/hhaapala/dart/space_shared

#dependencies:
#  js: any
#  unittest: any